### ISSUE TITLE
No "distort_param" in caffe.proto

### ISSUE THREAD

**Issue by Anhaoxu** [conner99/caffe#34]
@conner99 Hi, I'm test this branch these days in windows,but in my windows, it has an error.
`[libprotobuf ERROR ..\src\google\protobuf\text_format.cc:274] Error parsing text-format caffe.NetParameter: 29:19: Message type "caffe.TransformationParameter" has no field named "distort_param".`
Then,I found it has no distort_param in caffe.proto,so can you solve this problem?

**Comment by yuanwei0908** [comment]
so do i,how to address it,please
